//! Inert attribute macros for suppressing mutations generated by `cargo-gamma`.
//!
//! Every macro in this crate expands to the annotated item **unchanged**. They exist so that
//! `cargo-gamma` can see a suppression in the source, and so that malformed arguments are a
//! compile error in your crate rather than a suppression that silently does nothing — which is
//! the failure mode of regex-based exclusion in other tools.
//!
//! ```rust
//! #[gamma::skip]
//! fn hand_verified(x: u32) -> u32 {
//!     x + 1
//! }
//!
//! #[gamma::skip(arith, reason = "fixed-point math, checked by proptest")]
//! fn scaled(a: i64, b: i64) -> i64 {
//!     a * b / 1000
//! }
//! ```
//!
//! # Depending on it
//!
//! ```toml
//! [dev-dependencies]
//! cargo-gamma-attrs = "0.1"
//! ```
//!
//! The package is `cargo-gamma-attrs` but its library is named `gamma`, which is what lets the
//! attributes be written as `#[gamma::skip]` with no `use` and no rename in the manifest. That
//! spelling matters more than it looks: it is the same text as the comment form, so the two
//! channels stay character-for-character identical and one can become the other by deleting two
//! slashes.
//!
//! A dev-dependency is enough, since the attributes only ever appear in code being tested.
//!
//! # The vocabulary
//!
//! Arguments are the same selector language the command line and the config file use, so one name
//! learned is one name that works everywhere. A selector is a mutator name (`arith.add_to_sub`), a
//! family prefix (`arith`), a profile (`@arithmetic`), or an academic alias (`ROR`); `!` in front
//! removes one from the set, and selectors apply left to right, so `arith, !arith.add_to_sub`
//! means what it reads as. No arguments at all means every mutator.
//!
//! ```rust
//! // Every mutator.
//! #[gamma::skip]
//! fn everything() {}
//!
//! // One mutator, by its full name.
//! #[gamma::skip(relational.lt_to_le)]
//! fn one_mutator(a: u32, b: u32) -> bool {
//!     a < b
//! }
//!
//! // A whole family.
//! #[gamma::skip(literal)]
//! fn a_family() -> &'static str {
//!     "not asserted on"
//! }
//!
//! // A profile.
//! #[gamma::skip(@arithmetic)]
//! fn a_profile(a: i32, b: i32) -> i32 {
//!     a * b + 1
//! }
//!
//! // An academic alias, matched case-insensitively.
//! #[gamma::skip(ROR)]
//! fn an_alias(a: u32, b: u32) -> bool {
//!     a >= b
//! }
//!
//! // A family, minus one of its members.
//! #[gamma::skip(arith, !arith.add_to_sub)]
//! fn all_but_one(a: i32, b: i32) -> i32 {
//!     a * b - 1
//! }
//! ```
//!
//! Two optional named arguments may follow the selectors:
//!
//! - `reason = "..."` — why the suppression exists. It is carried into the report, so a reviewer
//!   meets the justification beside the number rather than having to go and find the line.
//! - `tag = "..."` — a label for grouping suppressions, so a project can audit "everything we
//!   skipped for performance" as a set.
//!
//! ```rust
//! #[gamma::skip(stmt, reason = "instrumentation only", tag = "telemetry")]
//! fn record(counter: &mut u64) {
//!     *counter += 1;
//! }
//! ```
//!
//! Both must be string literals. Writing `reason = performance` or `reason("...")` is a compile
//! error, which is the point: a suppression that does not parse should fail loudly rather than
//! quietly cover nothing.
//!
//! # The three macros
//!
//! [`macro@skip`] withdraws mutants. [`macro@expect_missed`] and [`macro@expect_caught`] assert
//! the opposite things about them and fail the run when the assertion breaks: the first is a
//! ratchet for a known gap, so that closing it is deliberate and visible rather than accidental,
//! and the second pins a test whose value someone wants protected from erosion.
//!
//! ```rust
//! // Records a gap. If someone later writes a test that kills these mutants, the run fails until
//! // the attribute is removed — so the gap closes on purpose, with the record cleaned up.
//! #[gamma::expect_missed(literal, reason = "log text is deliberately not asserted on")]
//! fn describe(n: usize) -> String {
//!     format!("processed {n} items")
//! }
//!
//! // Pins a guarantee. If a refactor weakens the suite until one of these mutants survives, the
//! // run fails immediately rather than after the score has slowly drifted.
//! #[gamma::expect_caught]
//! fn checksum(bytes: &[u8]) -> u32 {
//!     bytes.iter().fold(0u32, |acc, b| acc.wrapping_mul(31).wrapping_add(u32::from(*b)))
//! }
//!
//! // Both take the same selectors, so an expectation can be as narrow as a suppression.
//! #[gamma::expect_caught(relational, reason = "the boundary tests exist to catch exactly these")]
//! fn in_range(x: i32, low: i32, high: i32) -> bool {
//!     x >= low && x <= high
//! }
//! ```
//!
//! # Where they can go
//!
//! On any item, and on everything beneath it — so an attribute on a module covers the module, and
//! one on an `impl` covers every method in it:
//!
//! ```rust
//! #[gamma::skip(arith, reason = "generated fixed-point tables")]
//! mod tables {
//!     pub fn scale(x: i64) -> i64 {
//!         x * 4096
//!     }
//! }
//!
//! struct Cursor {
//!     at: usize,
//! }
//!
//! #[gamma::skip(reason = "exercised only through the fuzzer")]
//! impl Cursor {
//!     fn advance(&mut self) {
//!         self.at += 1;
//!     }
//!
//!     fn at_start(&self) -> bool {
//!         self.at == 0
//!     }
//! }
//! ```
//!
//! # Relationship to the comment form
//!
//! Attributes in statement and expression position are still unstable, so the primary channel for
//! surgical suppression is a comment that is *character-for-character* the attribute form:
//!
//! ```text
//! // #[gamma::skip(arith)]
//! let total = a * scale + offset;
//! ```
//!
//! When expression attributes stabilize, deleting the two slashes turns every such comment into
//! real Rust. This crate is what those comments become.
//!
//! The comment form takes exactly the same arguments, so nothing has to be relearned to move from
//! one to the other:
//!
//! ```text
//! // #[gamma::skip(relational, reason = "the bound is checked one frame later")]
//! if index < self.len {
//!     // #[gamma::skip(stmt, tag = "telemetry")]
//!     self.hits += 1;
//! }
//!
//! // #[gamma::expect_caught(@boundary)]
//! let clamped = value.min(limit);
//! ```
//!
//! The comment form is not validated by the compiler, since it is a comment — `cargo-gamma`
//! diagnoses a misspelled selector there instead, and refuses to treat an unrecognized directive
//! as a suppression that quietly did nothing.
//!
//! Choose the attribute when the unit being excused is a whole item, and the comment when it is one
//! statement or one expression inside an item that is otherwise worth mutating. A third channel,
//! `.cargo/gamma.toml`, is the right place for a policy that is about the project rather than about
//! any particular line.
//!
//! `#[mutants::skip]` is also honored, so a project moving from cargo-mutants keeps its existing
//! suppressions without editing a single file.

#![cfg_attr(coverage_nightly, feature(coverage_attribute))]
// Nothing in this crate can be reached by a coverage run. Its only caller is rustc, during the
// expansion of some *other* crate, and the counters a proc macro increments inside the compiler are
// never written to a profile the harness collects. Everything here is exercised instead by the
// doctests above and by the suppression tests in `cargo-gamma-lib`, which drive the real attributes
// through a real build; marking it off is the difference between an honest 100% and a figure with
// an unexplained hole in it.
#![cfg_attr(coverage_nightly, coverage(off))]
// A proc-macro crate's exported functions are `TokenStream -> TokenStream`; documenting each
// individually would be noise given the crate-level docs above.
#![allow(clippy::missing_const_for_fn, reason = "proc-macro entry points cannot be const")]

use proc_macro::{Delimiter, TokenStream, TokenTree};

/// Suppresses mutations on the annotated item and everything beneath it.
///
/// With no arguments, every mutator is suppressed. With arguments, only the listed selectors are:
/// a mutator name (`arith.add_to_sub`), a family prefix (`arith`), a profile (`@removal`), or an
/// academic alias (`ROR`).
///
/// # Examples
///
/// ```rust
/// // Nothing in here is mutated at all.
/// #[gamma::skip]
/// fn hand_verified(x: u32) -> u32 {
///     x + 1
/// }
///
/// // Only arithmetic is left alone; the relational mutants on `>` are still generated.
/// #[gamma::skip(arith, reason = "fixed-point, covered by proptest")]
/// fn positive_scaled(a: i64, b: i64) -> bool {
///     a * b / 1000 > 0
/// }
///
/// // A profile, minus one member, with a tag for auditing.
/// #[gamma::skip(@arithmetic, !arith.add_to_sub, tag = "hot-loop")]
/// fn blend(a: i32, b: i32) -> i32 {
///     a * b + (a - b)
/// }
/// ```
#[proc_macro_attribute]
pub fn skip(attr: TokenStream, item: TokenStream) -> TokenStream {
    inert("skip", attr, item)
}

/// Asserts that the selected mutants *survive*, and fails the run if any is killed.
///
/// This is a ratchet for known gaps: it records the gap so that closing it is a deliberate,
/// visible act rather than an accident. Unlike [`macro@skip`], the mutants are still generated and
/// still tested — what changes is which outcome is treated as a failure.
///
/// # Examples
///
/// ```rust
/// // Nobody asserts on this text today. When somebody starts to, the run fails until this
/// // attribute is deleted, so the record never outlives the gap it describes.
/// #[gamma::expect_missed(literal, reason = "log text is deliberately not asserted on")]
/// fn describe(n: usize) -> String {
///     format!("processed {n} items")
/// }
/// ```
#[proc_macro_attribute]
pub fn expect_missed(attr: TokenStream, item: TokenStream) -> TokenStream {
    inert("expect_missed", attr, item)
}

/// Asserts that the selected mutants are *killed*, and fails the run if any survives.
///
/// This pins a guarantee. A refactor that quietly weakens the suite fails the run at the line that
/// lost its cover, rather than showing up later as a slow drift in the overall score.
///
/// # Examples
///
/// ```rust
/// // Every mutant of this function must be caught by some test.
/// #[gamma::expect_caught]
/// fn checksum(bytes: &[u8]) -> u32 {
///     bytes.iter().fold(0u32, |acc, b| acc.wrapping_mul(31).wrapping_add(u32::from(*b)))
/// }
///
/// // Or just the boundary ones, because those are what the boundary tests exist for.
/// #[gamma::expect_caught(@boundary, reason = "guarded by the range tests")]
/// fn in_range(x: i32, low: i32, high: i32) -> bool {
///     x >= low && x <= high
/// }
/// ```
#[proc_macro_attribute]
pub fn expect_caught(attr: TokenStream, item: TokenStream) -> TokenStream {
    inert("expect_caught", attr, item)
}

/// Validates the argument list and returns the item untouched.
fn inert(name: &str, attr: TokenStream, item: TokenStream) -> TokenStream {
    match validate(attr) {
        Ok(()) => item,
        Err(message) => {
            let mut out = error(&format!("#[gamma::{name}]: {message}"));

            out.extend(item);
            out
        }
    }
}

/// Checks the structural shape of an argument list.
///
/// Selector *names* are not checked here: the registry lives in the tool, and duplicating it in a
/// proc macro would mean two lists that drift apart. `cargo gamma` reports unknown selectors as
/// hard errors with a spelling suggestion. What this does check is the shape that a human is
/// likely to get wrong without noticing — a `reason` or `tag` that is not a string.
fn validate(attr: TokenStream) -> Result<(), String> {
    let trees: Vec<TokenTree> = attr.into_iter().collect();
    let mut index = 0;

    while index < trees.len() {
        if let TokenTree::Ident(ident) = &trees[index] {
            let key = ident.to_string();

            if matches!(key.as_str(), "reason" | "tag") {
                let is_equals = matches!(trees.get(index + 1), Some(TokenTree::Punct(punct)) if punct.as_char() == '=');

                if !is_equals {
                    return Err(format!("`{key}` must be written as `{key} = \"...\"`"));
                }

                match trees.get(index + 2) {
                    Some(TokenTree::Literal(literal)) if literal.to_string().starts_with('"') => {}
                    _ => return Err(format!("`{key}` must be a string literal")),
                }

                index += 3;
                continue;
            }
        }

        if let TokenTree::Group(group) = &trees[index]
            && group.delimiter() == Delimiter::Parenthesis
        {
            validate(group.stream())?;
        }

        index += 1;
    }

    Ok(())
}

/// Builds a `compile_error!` invocation carrying `message`.
fn error(message: &str) -> TokenStream {
    let escaped = message.replace('\\', "\\\\").replace('"', "\\\"");

    format!("::core::compile_error!(\"{escaped}\");")
        .parse()
        .unwrap_or_else(|_| TokenStream::new())
}
