//! Translating a foreign configuration file into ours.

use core::fmt::Write as _;

use toml::{Table, Value};

use crate::Result;
use crate::error::error;

use super::Translation;
use super::lock_flags::{adjust_lock_flags, lock_flag_reason, substitute_lock_flag};

/// Where the foreign configuration lives.
pub(super) const SOURCE_PATH: &str = ".cargo/mutants.toml";

/// Where ours goes.
pub(super) const TARGET_PATH: &str = ".cargo/gamma.toml";

/// Translates a foreign configuration file into ours.
///
/// The input is parsed as generic TOML rather than into a schema, because the goal is to survive
/// *any* input — including keys from a version of that schema newer than this code — and a schema
/// would reject exactly the files that most need reporting.
pub fn translate(text: &str) -> Result<Translation> {
    let table: Table = toml::from_str(text).map_err(|cause| error!("{SOURCE_PATH} is not valid TOML: {}", cause.message()).usage())?;

    let mut out = Translation {
        text: String::from(
            "# Generated by `cargo gamma migrate` from .cargo/mutants.toml.\n\
             # Review before committing: the two tools do not mutate the same things, so a\n\
             # setting that carried over exactly may still mean something different.\n\n",
        ),
        ..Translation::default()
    };

    let mut reporters = String::new();

    for (key, value) in &table {
        match key.as_str() {
            // Keys we hold the same setting for, under a different name. The values carry across
            // unchanged, so these lines work as written.
            "examine_globs" => out.emit("files", key, value),
            "exclude_globs" => out.emit("exclude-files", key, value),
            "jobs" => out.emit("jobs", key, value),
            "timeout_multiplier" => out.emit("test-timeout-multiplier", key, value),
            "minimum_test_timeout" => out.emit("minimum-test-timeout", key, value),
            "build_timeout_multiplier" => out.emit("build-timeout-multiplier", key, value),
            "profile" => out.emit("profile", key, value),
            "features" => out.emit("features", key, value),
            "all_features" => out.emit("all-features", key, value),
            "no_default_features" => out.emit("no-default-features", key, value),
            "additional_cargo_args" => translate_cargo_args(&mut out, key, value),
            "test_package" => out.emit("test-packages", key, value),

            // Both name the runner: mutants uses "nextest"/"cargo", gamma uses a boolean flag `nextest`.
            "test_tool" => match value.as_str() {
                Some("nextest") => out.emit("nextest", key, &Value::from(true)),
                Some("cargo") => out.emit("nextest", key, &Value::from(false)),
                _ => out.emit("nextest", key, value),
            },

            // Both name the `Err(...)` payloads to try when a function returns `Result` and the
            // error type has no `Default`.
            "error_values" => out.emit("errors", key, value),

            // Settings whose behavior gamma already has, unconditionally. These need no key, which
            // is a different thing from being lost, and saying so is the whole point of the note.
            "cap_lints" => out.settled(key, value, "gamma always builds the instrumented tree with `--cap-lints=allow`"),
            "gitignore" => out.settled(key, value, "gamma always honors `.gitignore` when copying the tree"),
            "copy_vcs" => out.settled(key, value, "gamma never copies version control directories into the scratch tree"),
            "copy_target" => out.settled(key, value, "gamma keeps its own build directory and reuses it between runs"),

            // Recognized settings whose closest gamma behavior needs translation or explanation.
            "output" => out.settled(key, value, "gamma writes each report where you point it"),
            "test_workspace" => out.emit("test-workspace", key, value),
            "sharding" => out.settled(
                key,
                value,
                "gamma has one sharding algorithm; select a shard with `--shard-count` and `--shard-index`",
            ),

            // Deliberately not translated onto `cargo-test-args`, which looks like the match and is
            // not: gamma's key passes arguments to each test binary, whereas this one passes them
            // to `cargo test` itself. Carrying the value across put target selectors like `--tests`
            // in front of libtest, which rejects them, and the run then failed at the baseline with
            // nothing to point at. `--tests` in particular is already how gamma builds.
            "additional_cargo_test_args" => out.settled(
                key,
                value,
                "gamma already builds with `cargo test --no-run --tests`; anything else goes on `cargo-args` for cargo or `cargo-test-args` for the harness",
            ),

            // The source schema filters by matching a regex against the text of a generated mutant.
            // Gamma has no equivalent, and the substitutes are different in kind: `--mutators` chooses
            // which mutators run at all, and a `#[gamma::skip]` directive settles one site.
            "examine_re" | "exclude_re" => out.settled(key, value, "gamma has no regex filter; narrow `--mutators` or suppress the site"),

            "skip_calls" | "skip_calls_defaults" => out.settled(key, value, "gamma has no per-call skip list"),

            "html_report" => {
                let _ = writeln!(reporters, "html = {value}  # was {key}");
                out.translated += 1;
            }

            _ => out.preserve(key, value),
        }
    }

    if !reporters.is_empty() {
        out.text.push_str("\n[reporters]\n");
        out.text.push_str(&reporters);
    }

    if !out.settled.is_empty() {
        out.text.push_str(
            "\n# The following were recognized and need no setting here. Each line says why: some\n\
             # name behavior gamma always has, and the rest have no equivalent. Nothing is lost.\n",
        );

        for line in &out.settled {
            out.text.push_str(line);
        }
    }

    if !out.preserved.is_empty() {
        out.text.push_str(
            "\n# The following are not settings this tool knows, so their TOML values are recorded\n\
             # as TODOs rather than guessed at. Source comments and formatting are not retained.\n\
             # Delete them once you have decided what, if anything,\n\
             # replaces them.\n",
        );

        for line in &out.preserved {
            out.text.push_str(line);
        }
    }

    validate(&out.text)?;

    Ok(out)
}

/// Refuses a translation that gamma itself would not load.
///
/// The recognized values carry across unchanged, which is what makes the translated lines readable
/// beside the old file — but "unchanged" is not "accepted": the two tools agree on the spelling of
/// `minimum_test_timeout` and not on its domain, so a foreign `0`, which that tool takes as no floor
/// at all, becomes a gamma configuration that every later command rejects. The output is published
/// with no-clobber and lands in version control, so the failure would surface on the *next* command,
/// naming the config file rather than the migration that wrote it, with the migration already
/// reported as a success. Failing here costs the user a line to edit; failing there costs them the
/// file.
fn validate(text: &str) -> Result<()> {
    let Err(cause) = crate::config::Config::parse(text) else {
        return Ok(());
    };

    // The key gamma complains about is the useful half; the key it was translated from is what the
    // reader has in front of them.
    let blamed = blame(text, &cause).map_or_else(String::new, |(name, from)| format!(" (`{name}`, translated from `{from}`)"));

    Err(error!("the translated configuration would not load: {cause}{blamed}").usage())
}

/// The translated line a rejection is about, as the pair of names it carries.
fn blame(text: &str, message: &str) -> Option<(String, String)> {
    text.lines().find_map(|line| {
        let (setting, from) = line.split_once("  # was ")?;
        let name = setting.split_once(" =")?.0;

        message.contains(name).then(|| (name.to_owned(), from.to_owned()))
    })
}

/// Carries the extra cargo arguments across, minus the promise gamma cannot keep.
///
/// `--locked` and `--frozen` forbid writing the lockfile, and gamma has to write it: the guard
/// runtime becomes a dependency of every mutated package before anything is built. Copied across
/// verbatim, the migrated configuration failed on its first build and named the lockfile rather
/// than the flag, so the substitution happens here and says so on the following line.
fn translate_cargo_args(out: &mut Translation, key: &str, value: &Value) {
    let strings = value.as_array().and_then(|items| {
        items
            .iter()
            .map(|item| item.as_str().map(str::to_owned))
            .collect::<Option<Vec<String>>>()
    });

    let Some(args) = strings else {
        out.emit("cargo-args", key, value);
        return;
    };

    let (adjusted, substituted) = adjust_lock_flags(&args);

    out.emit("cargo-args", key, &Value::from(adjusted));

    if !substituted.is_empty() {
        let _ = writeln!(out.text, "# {}", lock_flag_reason(&substituted));
    }
}

/// Carries one `--cargo-arg` across, substituting a flag gamma cannot honor.
///
/// The flag is passed through to cargo verbatim in every other case: this is the escape hatch, and
/// guessing at what goes through it would defeat its purpose.
pub(super) fn cargo_arg(out: &mut Vec<String>, notes: &mut Vec<String>, value: Option<&String>) {
    let Some(value) = value else {
        notes.push("--cargo-arg needs a value".to_owned());
        return;
    };

    out.push("--cargo-arg".to_owned());

    let Some(replacement) = substitute_lock_flag(value) else {
        out.push(value.clone());
        return;
    };

    let note = lock_flag_reason(core::slice::from_ref(value));

    if out.iter().any(|arg| arg == replacement) {
        // The substitute is already on the line, so a second copy would only invite the question
        // of what the two meant. The flag it replaced still has to be dropped.
        let _removed = out.pop();
    } else {
        out.push(replacement.to_owned());
    }

    if !notes.contains(&note) {
        notes.push(note);
    }
}

#[cfg(test)]
mod tests {
    use super::super::command::translate_command;
    use super::*;

    #[test]
    fn globs_carry_over_under_their_new_names() {
        let out = translate("examine_globs = [\"src/**\"]\nexclude_globs = [\"tests/**\"]\n").expect("translates");

        assert!(out.text.contains("files = [\"src/**\"]"), "{}", out.text);
        assert!(out.text.contains("exclude-files = [\"tests/**\"]"), "{}", out.text);
        assert_eq!(out.translated, 2);
    }

    #[test]
    fn every_translated_line_names_the_key_it_came_from() {
        // The person reviewing this diff knows the old configuration, not the new one.
        let out = translate("examine_globs = [\"src/**\"]\n").expect("translates");

        assert!(out.text.contains("# was examine_globs"), "{}", out.text);
    }

    #[test]
    fn a_key_with_no_equivalent_is_recorded_with_its_reason() {
        // `exclude_re` matches the source tool's rendering of its own mutants, which gamma does not
        // produce, so there is nothing honest to translate it into. Dropping it would silently
        // un-suppress whatever it was suppressing.
        let out = translate("exclude_re = [\"replace .* with Default::default\"]\n").expect("translates");

        assert_eq!(out.translated, 0);
        assert_eq!(out.settled.len(), 1);
        assert!(out.preserved.is_empty(), "a key we recognize is not a TODO");
        assert!(out.text.contains("exclude_re"), "{}", out.text);
        assert!(out.text.contains("Default::default"), "the rendered TOML value must be retained");
    }

    #[test]
    fn the_sharding_note_names_the_two_supported_flags() {
        let out = translate("sharding = \"random\"\n").expect("translates");

        assert!(out.text.contains("--shard-count"), "{}", out.text);
        assert!(out.text.contains("--shard-index"), "{}", out.text);
    }

    /// The bug this guards: `all_features` was reported as having no equivalent when it has an
    /// exact one, so a migration silently dropped it and changed what the next run compiled.
    #[test]
    fn every_cargo_option_with_an_exact_equivalent_is_translated() {
        let out = translate(
            "all_features = true\nno_default_features = true\nprofile = \"mutants\"\nfeatures = [\"a\"]\n\
             additional_cargo_args = [\"--locked\"]\n\
             error_values = [\"anyhow!(\\\"m\\\")\"]\ntest_package = [\"ledger\"]\nbuild_timeout_multiplier = 3.0\n",
        )
        .expect("translates");

        assert_eq!(out.translated, 8, "{}", out.text);
        assert!(out.preserved.is_empty(), "{}", out.text);

        for expected in [
            "all-features = true",
            "no-default-features = true",
            "profile = \"mutants\"",
            "features = [\"a\"]",
            // `--locked` cannot survive: gamma writes the guard runtime into the manifest, so the
            // lockfile must change. `--offline` is the part of it a run can keep.
            "cargo-args = [\"--offline\"]",
            "errors = [",
            "test-packages = [\"ledger\"]",
            "build-timeout-multiplier = 3.0",
        ] {
            assert!(out.text.contains(expected), "missing `{expected}` in\n{}", out.text);
        }
    }

    /// A floor on the timeout is translated directly.
    #[test]
    fn a_timeout_floor_becomes_the_floor_and_not_a_fixed_budget() {
        let out = translate("minimum_test_timeout = 30.0\n").expect("translates");

        assert!(out.text.contains("minimum-test-timeout = 30.0"), "{}", out.text);
    }

    /// The two tools both have a key with "cargo test args" in the name, and they mean different
    /// things: the source passes them to `cargo test`, gamma passes them to each test binary.
    /// Translating one into the other put `--tests` in front of libtest, which rejects it, so the
    /// migrated config failed at the baseline with nothing useful to point at.
    #[test]
    fn cargo_test_arguments_are_not_translated_onto_the_harness_key_that_merely_looks_alike() {
        let out = translate("additional_cargo_test_args = [\"--tests\"]\n").expect("translates");

        assert_eq!(out.translated, 0, "{}", out.text);
        assert_eq!(out.settled.len(), 1, "{}", out.text);
        assert!(!out.text.contains("\ncargo-test-args = "), "{}", out.text);
    }

    /// Saying a setting "does nothing" when the behavior is unconditional sends people looking
    /// for a problem that is not there.
    #[test]
    fn a_setting_gamma_already_honors_is_reported_as_settled_not_as_a_gap() {
        let out = translate("cap_lints = true\ngitignore = true\ncopy_vcs = false\n").expect("translates");

        assert_eq!(out.settled.len(), 3);
        assert!(out.preserved.is_empty(), "{}", out.text);
        assert!(out.text.contains("always builds the instrumented tree"), "{}", out.text);
        assert!(out.text.contains("always honors `.gitignore`"), "{}", out.text);
    }

    /// The guarantee the command makes: every key in becomes exactly one key out.
    #[test]
    fn every_key_lands_in_exactly_one_bucket() {
        let out = translate("examine_globs = [\"src/**\"]\ncap_lints = true\nsome_future_key = 42\n").expect("translates");

        assert_eq!(out.translated, 1);
        assert_eq!(out.settled.len(), 1);
        assert_eq!(out.preserved.len(), 1);
        assert_eq!(out.total(), 3);
    }

    #[test]
    fn an_unknown_key_from_a_newer_foreign_schema_is_preserved_too() {
        // Parsing into a schema would reject this file outright, which is the opposite of useful:
        // the files most in need of migrating are the ones using features we have never seen.
        let out = translate("some_future_key = 42\n").expect("an unknown key must not stop the migration");

        assert_eq!(out.preserved.len(), 1);
        assert!(out.text.contains("# TODO: some_future_key"), "{}", out.text);
    }

    /// Unknown TOML is retained as a semantic value, not as an untouched source slice. This makes
    /// the reviewer's tradeoff explicit: the setting is visible, but comments and presentation from
    /// the foreign file cannot imply that the generated file preserved them.
    #[test]
    fn unknown_values_are_recorded_semantically_not_verbatim() {
        let out = translate("# source comment\nsome_future_key = [ 1, 2 ] # trailing comment\n").expect("translates");

        assert!(out.text.contains("# TODO: some_future_key = [1, 2]"), "{}", out.text);
        assert!(!out.text.contains("source comment"), "{}", out.text);
        assert!(!out.text.contains("trailing comment"), "{}", out.text);
    }

    #[test]
    fn the_generated_file_is_valid_gamma_configuration() {
        // A migration that emits something the tool then refuses to load is not a migration. This
        // covers every translated key at once, which matters because gamma's config denies unknown
        // fields: a name spelled wrong here fails this test rather than a user's next run.
        let out = translate(
            "examine_globs = [\"src/**\"]\nexclude_globs = [\"tests/**\"]\njobs = 4\ntimeout_multiplier = 3.0\n\
             minimum_test_timeout = 30.0\nbuild_timeout_multiplier = 2.0\nprofile = \"mutants\"\nfeatures = [\"a\"]\n\
             all_features = true\nno_default_features = true\nadditional_cargo_args = [\"--locked\"]\n\
             error_values = [\"E::X\"]\ntest_package = [\"ledger\"]\n\
             cap_lints = true\nexclude_re = [\"x\"]\nsome_future_key = 1\n",
        )
        .expect("translates");

        let config = crate::config::Config::parse(&out.text).expect("the generated file must load");

        assert_eq!(config.files, vec!["src/**".to_owned()]);
        assert_eq!(config.exclude_files, vec!["tests/**".to_owned()]);
        assert_eq!(config.jobs, Some(4));
        assert_eq!(config.test_timeout_multiplier, Some(3.0));
        assert_eq!(config.minimum_test_timeout, Some(30.0));
        assert_eq!(config.build_timeout_multiplier, Some(2.0));
        assert_eq!(config.profile, Some("mutants".to_owned()));
        assert_eq!(config.features, vec!["a".to_owned()]);
        assert_eq!(config.all_features, Some(true));
        assert_eq!(config.no_default_features, Some(true));
        assert_eq!(config.cargo_args, vec!["--offline".to_owned()]);
        assert_eq!(config.errors, vec!["E::X".to_owned()]);
        assert_eq!(config.test_packages, vec!["ledger".to_owned()]);
    }

    /// The two tools spell `minimum_test_timeout` the same and mean different domains by it: zero
    /// is "no floor" there and rejected here. Publishing it would report success, land a file in
    /// version control with no-clobber, and fail on the *next* command naming the config rather
    /// than the migration that wrote it.
    #[test]
    fn a_value_gamma_would_reject_stops_the_translation_rather_than_being_published() {
        let cause = translate("minimum_test_timeout = 0\n").expect_err("a configuration that cannot load");

        assert!(cause.is_usage(), "{cause}");

        let text = cause.to_string();

        assert!(text.contains("minimum-test-timeout"), "{text}");
        assert!(
            text.contains("minimum_test_timeout"),
            "the foreign key it came from is what the reader has: {text}"
        );
    }

    #[test]
    fn malformed_input_is_a_usage_error() {
        let cause = translate("jobs = \n").expect_err("malformed input must be rejected");

        assert!(cause.is_usage(), "{cause}");
    }

    /// The same substitution on the command line, where the flag arrives inside `--cargo-arg`.
    #[test]
    fn a_lockfile_promise_passed_through_cargo_arg_is_substituted_with_a_note() {
        let args = ["cargo", "mutants", "-C", "--locked", "-C", "--locked"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run --cargo-arg --offline");
        assert_eq!(notes.len(), 1, "one decision, said once: {notes:?}");
        assert!(notes[0].contains("--offline"), "{notes:?}");
        assert!(notes[0].contains("gamma_rt"), "the note must say what forces it: {notes:?}");
    }

    /// Anything else handed to cargo goes through untouched: this is the escape hatch, and a
    /// translator guessing at what goes through it defeats the purpose.
    #[test]
    fn any_other_cargo_argument_goes_through_untouched() {
        let args = ["cargo", "mutants", "--cargo-arg", "--target-dir=/tmp/x"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run --cargo-arg --target-dir=/tmp/x");
        assert!(notes.is_empty(), "{notes:?}");
    }

    /// `cargo_arg` is shared by both `-C` and `--cargo-arg`. It must not emit a gamma flag until
    /// it has a source value to pair with it.
    #[test]
    fn a_missing_cargo_argument_is_reported_without_a_dangling_destination_flag() {
        let mut out = vec!["cargo".to_owned(), "gamma".to_owned(), "run".to_owned()];
        let mut notes = Vec::new();

        cargo_arg(&mut out, &mut notes, None);

        assert_eq!(out, ["cargo", "gamma", "run"].map(str::to_owned));
        assert_eq!(notes, ["--cargo-arg needs a value"].map(str::to_owned));
    }
}
