//! Porting a cargo-mutants project, once, reviewably.
//!
//! Gamma deliberately reads neither cargo-mutants' configuration file nor its flags: the two tools
//! have different mutant catalogs, so honouring another tool's suppressions silently would mean its
//! settings quietly changing which mutants this one skips, and therefore quietly changing the score.
//! Migration is the alternative to that silence.
//!
//! The rules the translator holds itself to:
//!
//! **Nothing is ever dropped.** A key this tool cannot express becomes a `TODO` comment carrying the
//! original text verbatim. A migration that silently discards a setting is exactly the failure mode
//! the whole design is trying to avoid.
//!
//! **Every line says where it came from.** The output is meant to be read by someone who knows the
//! old configuration and not the new one, so each translated line is annotated with the key it
//! replaces.
//!
//! **Nothing is overwritten.** An existing `gamma.toml` stops the migration rather than being
//! replaced, because the thing being overwritten is the thing that took someone an afternoon.

mod paths;
mod translation;

use core::fmt::Write as _;
use toml::Table;

use crate::Result;
use crate::error::error;

pub use paths::Paths;
pub use translation::Translation;

/// Where cargo-mutants keeps its configuration.
const SOURCE_PATH: &str = ".cargo/mutants.toml";

/// Where ours goes.
const TARGET_PATH: &str = ".cargo/gamma.toml";

/// Translates a cargo-mutants configuration file into ours.
///
/// The input is parsed as generic TOML rather than into a schema, because the goal is to survive
/// *any* input — including keys from a cargo-mutants version newer than this code — and a schema
/// would reject exactly the files that most need reporting.
pub fn translate(text: &str) -> Result<Translation> {
    let table: Table =
        toml::from_str(text).map_err(|cause| error!("{SOURCE_PATH} is not valid TOML: {}", cause.message()).usage())?;

    let mut out = Translation {
        text: String::from(
            "# Generated by `cargo gamma migrate` from .cargo/mutants.toml.\n\
             # Review before committing: the two tools do not mutate the same things, so a\n\
             # setting that carried over exactly may still mean something different.\n\n",
        ),
        ..Translation::default()
    };

    let mut reporters = String::new();

    for (key, value) in &table {
        match key.as_str() {
            // Keys we hold the same setting for, under a different name. The values carry across
            // unchanged, so these lines work as written.
            "examine_globs" => out.emit("files", key, value),
            "exclude_globs" => out.emit("exclude-files", key, value),
            "jobs" => out.emit("jobs", key, value),
            "timeout_multiplier" => out.emit("timeout-multiplier", key, value),
            "minimum_test_timeout" => out.emit("minimum-test-timeout", key, value),
            "build_timeout_multiplier" => out.emit("build-timeout-multiplier", key, value),
            "profile" => out.emit("profile", key, value),
            "features" => out.emit("features", key, value),
            "all_features" => out.emit("all-features", key, value),
            "no_default_features" => out.emit("no-default-features", key, value),
            "additional_cargo_args" => out.emit("cargo-args", key, value),
            "test_package" => out.emit("test-packages", key, value),

            // Both name the `Err(...)` payloads to try when a function returns `Result` and the
            // error type has no `Default`.
            "error_values" => out.emit("errors", key, value),

            // Settings whose behaviour gamma already has, unconditionally. These need no key, which
            // is a different thing from being lost, and saying so is the whole point of the note.
            "cap_lints" => out.settled(key, value, "gamma always builds the instrumented tree with `--cap-lints=allow`"),
            "gitignore" => out.settled(key, value, "gamma always honours `.gitignore` when copying the tree"),
            "copy_vcs" => out.settled(key, value, "gamma never copies version control directories into the scratch tree"),
            "copy_target" => out.settled(key, value, "gamma keeps its own build directory and reuses it between runs"),

            // Recognised, and genuinely absent here.
            "output" => out.settled(key, value, "gamma writes each report where you point it"),
            "test_workspace" => out.settled(key, value, "no config key; pass `--test-workspace` on the command line"),
            "test_tool" => out.settled(key, value, "gamma runs `cargo test`; nextest is not supported"),
            "sharding" => out.settled(key, value, "gamma has one sharding algorithm; select a shard with `--shard`"),

            // Deliberately not translated onto `cargo-test-args`, which looks like the match and is
            // not: gamma's key passes arguments to each test binary, whereas this one passes them
            // to `cargo test` itself. Carrying the value across put target selectors like `--tests`
            // in front of libtest, which rejects them, and the run then failed at the baseline with
            // nothing to point at. `--tests` in particular is already how gamma builds.
            "additional_cargo_test_args" => out.settled(
                key,
                value,
                "gamma already builds with `cargo test --no-run --tests`; anything else goes on `cargo-args` for cargo or `cargo-test-args` for the harness",
            ),

            // cargo-mutants filters by matching a regex against the text of a generated mutant.
            // Gamma has no equivalent, and the substitutes are different in kind: `ops` chooses
            // which mutators run at all, and a `#[gamma::skip]` directive settles one site.
            "examine_re" | "exclude_re" => out.settled(key, value, "gamma has no regex filter; narrow `ops` or suppress the site"),

            "skip_calls" | "skip_calls_defaults" => out.settled(key, value, "gamma has no per-call skip list"),

            "html_report" => {
                let _ = writeln!(reporters, "html = {value}  # was {key}");
                out.translated += 1;
            }

            _ => out.preserve(key, value),
        }
    }

    if !reporters.is_empty() {
        out.text.push_str("\n[reporters]\n");
        out.text.push_str(&reporters);
    }

    if !out.settled.is_empty() {
        out.text.push_str(
            "\n# The following were recognised and need no setting here. Each line says why: some\n\
             # name behaviour gamma always has, and the rest have no equivalent. Nothing is lost.\n",
        );

        for line in &out.settled {
            out.text.push_str(line);
        }
    }

    if !out.preserved.is_empty() {
        out.text.push_str(
            "\n# The following are not settings this tool knows, so they are preserved verbatim\n\
             # rather than guessed at. Delete them once you have decided what, if anything,\n\
             # replaces them.\n",
        );

        for line in &out.preserved {
            out.text.push_str(line);
        }
    }

    Ok(out)
}

/// Translates a `cargo mutants` command line into the equivalent `cargo gamma` one.
///
/// This exists because the CLI was redesigned rather than copied, which turns every CI workflow in
/// the wild into a small migration cost. Handing back the translated line makes that cost a command
/// rather than an afternoon of reading two help texts side by side.
///
/// Unrecognised flags are returned as notes rather than guessed at: a wrong translation that looks
/// right is worse than an honest gap.
#[must_use]
pub fn translate_command(args: &[String]) -> (Vec<String>, Vec<String>) {
    let mut out = vec!["cargo".to_owned(), "gamma".to_owned(), "run".to_owned()];
    let mut notes = Vec::new();
    let mut rest = args.iter().skip_while(|arg| *arg == "cargo" || *arg == "mutants");

    // A macro rather than a closure: both this and the arms below need `rest`, and a closure would
    // hold the only mutable borrow of it for the whole loop.
    macro_rules! take {
        ($flag:expr) => {{
            out.push($flag.to_owned());

            if let Some(value) = rest.next() {
                out.push(value.clone());
            }
        }};
    }

    while let Some(arg) = rest.next() {
        match arg.as_str() {
            "-f" | "--file" => take!("--file"),
            "-e" | "--exclude" => take!("--exclude-file"),
            "-j" | "--jobs" => take!("-j"),
            "-d" | "--dir" => take!("--dir"),
            "--timeout" => take!("--timeout"),
            "--timeout-multiplier" => take!("--timeout-multiplier"),
            "--minimum-test-timeout" => take!("--minimum-test-timeout"),
            "--build-timeout" => take!("--build-timeout"),
            "--build-timeout-multiplier" => take!("--build-timeout-multiplier"),
            "-D" | "--in-diff" => take!("--in-diff"),
            "-p" | "--package" => take!("--package"),
            "--test-package" => take!("--test-package"),
            "--error" => take!("--error"),
            "-F" | "--features" => take!("--features"),
            "--profile" => take!("--profile"),
            "-C" | "--cargo-arg" => take!("--cargo-arg"),
            "--cargo-test-arg" => take!("--cargo-test-arg"),
            "--iterate" => take!("--iterate"),
            "--all-features" => out.push("--all-features".to_owned()),
            "--no-default-features" => out.push("--no-default-features".to_owned()),
            // cargo-mutants spells this as a flag taking a boolean; gamma's is a plain flag.
            "--test-workspace" => match rest.next().map(String::as_str) {
                Some("true") => out.push("--test-workspace".to_owned()),
                Some("false") => {}
                _ => notes.push("--test-workspace needs true or false".to_owned()),
            },
            "--workspace" => out.push("--workspace".to_owned()),
            "--leak-dirs" => out.push("--leak-dirs".to_owned()),
            "--no-config" => out.push("--no-config".to_owned()),
            "--config" => take!("--config"),

            // `k/n` becomes two flags, because one option that silently means two numbers is the
            // kind of thing people get backwards.
            "--shard" => match rest.next().and_then(|spec| spec.split_once('/')) {
                Some((index, count)) => {
                    out.push("--shard-index".to_owned());
                    out.push(index.to_owned());
                    out.push("--shard-count".to_owned());
                    out.push(count.to_owned());
                }

                None => notes.push("--shard needs an INDEX/COUNT value".to_owned()),
            },

            "--list" => {
                "list".clone_into(&mut out[2]);
                out.push("mutants".to_owned());
            }

            "--json" => out.push("--json".to_owned()),

            // Gamma orders mutants deterministically by design, which is what makes sharding stable
            // across runs, so there is nothing to turn off.
            "--no-shuffle" | "--shuffle" => {
                notes.push(format!("{arg} dropped: gamma's mutant order is always deterministic"));
            }

            "--baseline" => match rest.next().map(String::as_str) {
                Some("skip") => out.push("--no-baseline".to_owned()),
                Some(other) => notes.push(format!("--baseline {other} is the default")),
                None => notes.push("--baseline needs a value".to_owned()),
            },

            other if other.starts_with('-') => notes.push(format!("{other} has no gamma equivalent")),

            other => notes.push(format!("ignored positional argument `{other}`")),
        }
    }

    (out, notes)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn globs_carry_over_under_their_new_names() {
        let out = translate("examine_globs = [\"src/**\"]\nexclude_globs = [\"tests/**\"]\n").expect("translates");

        assert!(out.text.contains("files = [\"src/**\"]"), "{}", out.text);
        assert!(out.text.contains("exclude-files = [\"tests/**\"]"), "{}", out.text);
        assert_eq!(out.translated, 2);
    }

    #[test]
    fn every_translated_line_names_the_key_it_came_from() {
        // The person reviewing this diff knows the old configuration, not the new one.
        let out = translate("examine_globs = [\"src/**\"]\n").expect("translates");

        assert!(out.text.contains("# was examine_globs"), "{}", out.text);
    }

    #[test]
    fn a_key_with_no_equivalent_survives_verbatim_with_its_reason() {
        // `exclude_re` matches cargo-mutants' rendering of its own mutants, which gamma does not
        // produce, so there is nothing honest to translate it into. Dropping it would silently
        // un-suppress whatever it was suppressing.
        let out = translate("exclude_re = [\"replace .* with Default::default\"]\n").expect("translates");

        assert_eq!(out.translated, 0);
        assert_eq!(out.settled.len(), 1);
        assert!(out.preserved.is_empty(), "a key we recognise is not a TODO");
        assert!(out.text.contains("exclude_re"), "{}", out.text);
        assert!(out.text.contains("Default::default"), "the original text must survive verbatim");
    }

    /// The bug this guards: `all_features` was reported as having no equivalent when it has an
    /// exact one, so a migration silently dropped it and changed what the next run compiled.
    #[test]
    fn every_cargo_option_with_an_exact_equivalent_is_translated() {
        let out = translate(
            "all_features = true\nno_default_features = true\nprofile = \"mutants\"\nfeatures = [\"a\"]\n\
             additional_cargo_args = [\"--locked\"]\n\
             error_values = [\"anyhow!(\\\"m\\\")\"]\ntest_package = [\"ledger\"]\nbuild_timeout_multiplier = 3.0\n",
        )
        .expect("translates");

        assert_eq!(out.translated, 8, "{}", out.text);
        assert!(out.preserved.is_empty(), "{}", out.text);

        for expected in [
            "all-features = true",
            "no-default-features = true",
            "profile = \"mutants\"",
            "features = [\"a\"]",
            "cargo-args = [\"--locked\"]",
            "errors = [",
            "test-packages = [\"ledger\"]",
            "build-timeout-multiplier = 3.0",
        ] {
            assert!(out.text.contains(expected), "missing `{expected}` in\n{}", out.text);
        }
    }

    /// A floor on the timeout is not a fixed timeout, and gamma has a key for each.
    #[test]
    fn a_timeout_floor_becomes_the_floor_and_not_a_fixed_budget() {        let out = translate("minimum_test_timeout = 30.0\n").expect("translates");

        assert!(out.text.contains("minimum-test-timeout = 30.0"), "{}", out.text);
        assert!(!out.text.contains("\ntimeout = "), "{}", out.text);
    }

    /// The two tools both have a key with "cargo test args" in the name, and they mean different
    /// things: cargo-mutants passes them to `cargo test`, gamma passes them to each test binary.
    /// Translating one into the other put `--tests` in front of libtest, which rejects it, so the
    /// migrated config failed at the baseline with nothing useful to point at.
    #[test]
    fn cargo_test_arguments_are_not_translated_onto_the_harness_key_that_merely_looks_alike() {
        let out = translate("additional_cargo_test_args = [\"--tests\"]\n").expect("translates");

        assert_eq!(out.translated, 0, "{}", out.text);
        assert_eq!(out.settled.len(), 1, "{}", out.text);
        assert!(!out.text.contains("\ncargo-test-args = "), "{}", out.text);
    }

    /// Saying a setting "does nothing" when the behaviour is unconditional sends people looking
    /// for a problem that is not there.
    #[test]
    fn a_setting_gamma_already_honours_is_reported_as_settled_not_as_a_gap() {
        let out = translate("cap_lints = true\ngitignore = true\ncopy_vcs = false\n").expect("translates");

        assert_eq!(out.settled.len(), 3);
        assert!(out.preserved.is_empty(), "{}", out.text);
        assert!(out.text.contains("always builds the instrumented tree"), "{}", out.text);
        assert!(out.text.contains("always honours `.gitignore`"), "{}", out.text);
    }

    /// The guarantee the command makes: every key in becomes exactly one key out.
    #[test]
    fn every_key_lands_in_exactly_one_bucket() {
        let out = translate("examine_globs = [\"src/**\"]\ncap_lints = true\nsome_future_key = 42\n").expect("translates");

        assert_eq!(out.translated, 1);
        assert_eq!(out.settled.len(), 1);
        assert_eq!(out.preserved.len(), 1);
        assert_eq!(out.total(), 3);
    }

    #[test]
    fn an_unknown_key_from_a_newer_cargo_mutants_is_preserved_too() {
        // Parsing into a schema would reject this file outright, which is the opposite of useful:
        // the files most in need of migrating are the ones using features we have never seen.
        let out = translate("some_future_key = 42\n").expect("an unknown key must not stop the migration");

        assert_eq!(out.preserved.len(), 1);
        assert!(out.text.contains("# TODO: some_future_key"), "{}", out.text);
    }

    #[test]
    fn the_generated_file_is_valid_gamma_configuration() {
        // A migration that emits something the tool then refuses to load is not a migration. This
        // covers every translated key at once, which matters because gamma's config denies unknown
        // fields: a name spelled wrong here fails this test rather than a user's next run.
        let out = translate(
            "examine_globs = [\"src/**\"]\nexclude_globs = [\"tests/**\"]\njobs = 4\ntimeout_multiplier = 3.0\n\
             minimum_test_timeout = 30.0\nbuild_timeout_multiplier = 2.0\nprofile = \"mutants\"\nfeatures = [\"a\"]\n\
             all_features = true\nno_default_features = true\nadditional_cargo_args = [\"--locked\"]\n\
             error_values = [\"E::X\"]\ntest_package = [\"ledger\"]\n\
             cap_lints = true\nexclude_re = [\"x\"]\nsome_future_key = 1\n",
        )
        .expect("translates");

        let config = crate::config::Config::parse(&out.text).expect("the generated file must load");

        assert_eq!(config.files, vec!["src/**".to_owned()]);
        assert_eq!(config.exclude_files, vec!["tests/**".to_owned()]);
        assert_eq!(config.jobs, Some(4));
        assert_eq!(config.timeout_multiplier, Some(3.0));
        assert_eq!(config.minimum_test_timeout, Some(30.0));
        assert_eq!(config.build_timeout_multiplier, Some(2.0));
        assert_eq!(config.profile, Some("mutants".to_owned()));
        assert_eq!(config.features, vec!["a".to_owned()]);
        assert_eq!(config.all_features, Some(true));
        assert_eq!(config.no_default_features, Some(true));
        assert_eq!(config.cargo_args, vec!["--locked".to_owned()]);
        assert_eq!(config.errors, vec!["E::X".to_owned()]);
        assert_eq!(config.test_packages, vec!["ledger".to_owned()]);

        // The floor must not have become a fixed budget, which is a different setting.
        assert_eq!(config.timeout, None);
    }

    #[test]
    fn malformed_input_is_a_usage_error() {
        let cause = translate("jobs = \n").expect_err("malformed input must be rejected");

        assert!(cause.is_usage(), "{cause}");
    }

    #[test]
    fn a_command_line_is_translated_flag_by_flag() {
        let args = ["cargo", "mutants", "--file", "src/**", "-j", "4"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run --file src/** -j 4");
        assert!(notes.is_empty(), "{notes:?}");
    }

    #[test]
    fn a_shard_becomes_two_explicit_flags() {
        // `3/8` reads as a fraction, and people write the two numbers the wrong way round often
        // enough that spelling them out is worth the extra characters.
        let args = ["cargo", "mutants", "--shard", "3/8"].map(str::to_owned);
        let (out, _) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run --shard-index 3 --shard-count 8");
    }

    #[test]
    fn listing_becomes_the_list_subcommand() {
        let args = ["cargo", "mutants", "--list", "--json"].map(str::to_owned);
        let (out, _) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma list mutants --json");
    }

    #[test]
    fn skipping_the_baseline_carries_over() {
        let args = ["cargo", "mutants", "--baseline", "skip"].map(str::to_owned);
        let (out, _) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run --no-baseline");
    }

    #[test]
    fn an_unrecognised_flag_becomes_a_note_rather_than_a_guess() {
        // A translation that looks right and is wrong will be copied into CI and believed.
        let args = ["cargo", "mutants", "--cap-lints", "true"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run");
        assert!(notes.iter().any(|note| note.contains("--cap-lints")), "{notes:?}");
    }

    #[test]
    fn shuffling_flags_are_dropped_with_an_explanation() {
        let args = ["cargo", "mutants", "--no-shuffle"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run");
        assert!(notes[0].contains("deterministic"), "{notes:?}");
    }

    #[test]
    fn a_report_destination_becomes_a_reporters_table() {
        // cargo-mutants writes its whole output tree under one directory; gamma points each report
        // at a path of its own. `output` therefore has no equivalent and is commented out, while
        // `html_report` does have one and moves into `[reporters]`.
        let out = translate("output = \"target/mutants\"\nhtml_report = \"target/report.html\"\n").expect("translates");

        assert!(out.text.contains("[reporters]"), "{}", out.text);
        assert!(out.text.contains("html = \"target/report.html\""), "{}", out.text);
        assert!(out.text.contains("# output ="), "the untranslatable key must survive as a comment");

        let config = crate::config::Config::parse(&out.text).expect("the generated file must load");

        assert_eq!(config.reporters.html.as_deref(), Some(camino::Utf8Path::new("target/report.html")));
    }

    #[test]
    fn a_test_workspace_flag_set_to_false_translates_to_nothing() {
        // cargo-mutants spells this as a flag taking a boolean, so `false` is a real spelling of
        // the default. Emitting `--test-workspace` for it would widen every run that used it.
        let args = ["cargo", "mutants", "--test-workspace", "false"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run");
        assert!(notes.is_empty(), "{notes:?}");
    }

    #[test]
    fn a_test_workspace_flag_with_no_boolean_becomes_a_note() {
        let args = ["cargo", "mutants", "--test-workspace"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run");
        assert!(notes.iter().any(|note| note.contains("--test-workspace")), "{notes:?}");
    }

    #[test]
    fn a_shard_without_a_value_becomes_a_note_rather_than_a_broken_command() {
        // Half a shard specification would produce a command line that fails at parse time in CI,
        // which is a worse place to find out than the migration itself.
        let args = ["cargo", "mutants", "--shard"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run");
        assert!(notes.iter().any(|note| note.contains("INDEX/COUNT")), "{notes:?}");
    }

    #[test]
    fn a_baseline_value_that_is_already_the_default_becomes_a_note() {
        let args = ["cargo", "mutants", "--baseline", "run"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run");
        assert!(notes.iter().any(|note| note.contains("default")), "{notes:?}");
    }

    #[test]
    fn a_baseline_flag_with_no_value_becomes_a_note() {
        let args = ["cargo", "mutants", "--baseline"].map(str::to_owned);
        let (out, notes) = translate_command(&args);

        assert_eq!(out.join(" "), "cargo gamma run");
        assert!(notes.iter().any(|note| note.contains("--baseline")), "{notes:?}");
    }
}
